config/routes.rb
Rails.application.routes.draw do
  get '/sign_up' => 'user#new', as: :sign_up
  post'/sign_up' => 'user#create'

  get '/sign_in' => 'static_pages#new', as: :sign_in
  post '/sign_in' => 'static_pages#create'

  root to: 'static_pages#home'

  delete '/sign_out' => 'static_pages#destroy', as: :sign_out
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true
  validates :email, format: { with: VALID_EMAIL_REGEX, message: 'value is invalid'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sign_in_controller.rb
class SignInController < ApplicationController
  def new
    if session[:user_id]
      flash[:success] = 'you have already signed in'
      redirect_to root_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.find_by email: params[:user][:email]
    if @user.present?
      if @user.authenticate(params[:user][:password])
        login(@user)
        flash[:success] = 'Sign in successfully'
        redirect_to root_path
      else
        flash.now[:danger] = 'Wrong password'
        render :new
      end
    else
      @user = User.new user_params
      flash.now[:danger] = 'Cant find user with email'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:suscess] = 'You are sign out successfully'
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit :email, :password
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def new
    if session[:user_id]
      flash[:success] = 'you have already signed in'
      redirect_to root_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.find_by email: params[:user][:email]
    if @user.present?
      if @user.authenticate(params[:user][:password])
        login(@user)
        flash[:success] = 'Sign in successfully'
        redirect_to root_path
      else
        flash.now[:danger] = 'Wrong password'
        render :new
      end
    else
      @user = User.new user_params
      flash.now[:danger] = 'Cant find user with email'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:suscess] = 'You are sign out successfully'
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit :email, :password
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
    @user = User.new
  end

   def create
     @user = User.new user_params
     if @user.save
       UserMailer.welcome_email(@user).deliver
       flash[:success] = 'You are signed up suscessfully'
       redirect_to root_path
     else
       flash.now[:danger] = 'Something went wrong'
       render :new
     end
   end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confimation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login user
    session[:user_id] = user.id
  end

  def current_user
    @current_user = User.find_by id: session[:user_id]
  end
end

app/helpers/sign_in_helper.rb
module SignInHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="container">
  <p>© Company 2017-2018</p>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <%= link_to 'Blog', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav ml-auto">
      <% if current_user.present? %>
        <li>
          <%= link_to 'Sign out', sign_out_path, class: 'nav-link', method: :delete, data: {confirm: "are you sure"} %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to 'Sign in', sign_in_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Sign up', sign_up_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <main role='main'>
      <%= render 'layouts/flash' %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/create.html.erb
<h1>SignIn#create</h1>
<p>Find me in app/views/sign_in/create.html.erb</p>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Hello, world!</h1>
    <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
    <p>
      <a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a>
    </p>
  </div>
</div>

app/views/static_pages/new.html.erb
<div class='row justify-content-center align-items-center h-100'>
  <div class='col col-sm-6 col-md-6 col-lg-4 col-xl-3'>
    <%= form_for @user, url: '/sign_in' do |f| %>
    <div class="form-group">
      <%=f.label :email %>
      <%=f.text_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%=f.label :password %>
      <%=f.text_field :password, class: 'form-control' %>
    </div>
      <%= f.submit 'Log in', class: 'btn btn-primary'%>
      <%= link_to 'Create User', sign_up_path, class: 'btn btn-secondary' %>
    <% end %>
  </div>
</div>

app/views/user/create.html.erb
<h1>SignUp#create</h1>
<p>Find me in app/views/sign_up/create.html.erb</p>

app/views/user/new.html.erb
<div class='row justify-content-center align-items-center h-100'>
  <div class='col col-sm-6 col-md-6 col-lg-4 col-xl-3'>
    <%= form_for @user, url: '/sign_up' do |f| %>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
    <div class="form-group">
      <%=f.label :name %>
      <%=f.text_field :name, class: 'form-control' %>
      <% if @user.errors.full_messages_for(:name).present?%>
        <ul>
          <% @user.errors.full_messages_for(:name).each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <div class="form-group">
      <%=f.label :email %>
      <%=f.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%=f.label :password %>
      <%=f.text_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%=f.label :password_confimation %>
      <%=f.text_field :password, class: 'form-control' %>
    </div>

    <%= f.submit class: 'btn btn-primary'%>
  <% end %>
</div>
</div>